kind: Deployment
apiVersion: apps/v1
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-pod
  template:
    metadata:
      labels:
        app: app-pod
    spec:
      containers:
        - name: app-container
          ports:
            - name: app-pod-port
              containerPort: 8081
              protocol: TCP
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
---
kind: Service
apiVersion: v1
metadata:
  name: app-service
spec:
ports:
  - name: app-ser-port
    port: 8081
    protocol: TCP
    targetPort: 8081
selector:
  app: demo-app