kind: Deployment
apiVersion: apps/v1
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-pod
  template:
    metadata:
      labels:
        app: app-pod
    spec:
      containers:
        - name: app-container
          ports:
            - name: app-pod-port
              containerPort: 8081
              protocol: TCP
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
---
kind: Service
apiVersion: v1
metadata:
  name: app-service
spec:
ports:
  - name: app-ser-port
    port: 8081
    protocol: TCP
    targetPort: 8081
selector:
  app: demo-app

---
kind: BuildConfig
metadata:
  name: devops-app
  labels:
    app: devops-app
spec:
  source:
    type: Git
    git:
      uri: https://github.com/murali94k/Openshift_Devops.git
    contextDir: Openshift_Devops
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile    # Look for Dockerfile in: gitUri/contextDir/dockerfilePath
  output:
    to:
      kind: ImageStreamTag
      name: devops-app:latest