kind: Service
apiVersion: helm.openshift.io/v1beta1
metadata:
  labels:
    {{- include "charts.labels" . | nindent 4}}
  name: {{ .Values.service.name}}
spec:
  ports:
  - name: app-ser-port
    port: {{ .Values.service.port}}
    protocol: TCP
    targetPort: {{ .Values.service.targetport}}
selector:
  {{- include "charts.selectorLabels" . | nindent 4}}