kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: demo-backend
  namespace: demo-project
  labels:
    app: demo-backend
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'backend-api:latest'
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  source:
    type: Git
    git:
      uri: 'https://github.com/murali94k/Backend-API.git'
  triggers:
    - type: GitHub
      github:
        secret: "dummy-secret" 
    - type: Generic
      generic:
        secret: "dummy-secret" 
    - type: ConfigChange
  runPolicy: Serial
