kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: demo-backend
  namespace: demo-project
  labels:
    app: demo-backend
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'demo-backend:latest'
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'python:3.9-ubi8'
  source:
    type: Git
    git:
      uri: 'https://github.com/murali94k/Backend-API.git'
  triggers:
    - type: GitHub
      github:
        secret: yxbDF35SQY9OgAdvvy4s
    - type: Generic
      generic:
        secret: IMKHURpq6wAQpHEiHYsL
    - type: ConfigChange
    - type: ImageChange
      imageChange: {}
  runPolicy: Serial
