kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: demo-backend
  namespace: demo-project
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'demo-backend:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/murali94k/Backend-API.git'
      ref: main
    contextDir: /
  runPolicy: Serial
